# Signup a new user
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

# Login the user
POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###

# Admin Login
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "adminuser",
    "email" : "admin@example.com",
    "password" : "AdminPass123",
    "isAdmin": true
}

# Copy the token from the response and replace <ADMIN-JWT-TOKEN-HERE> in the admin tests below.

###

# Get all users (Requires authentication)
GET http://localhost:8081/user/getAll
Content-Type: application/json
Authorization: Bearer <67efe163fe3afbe0781fd623>

###

# Edit user details (Requires authentication)
POST http://localhost:8081/user/editUser
Content-Type: application/json 
Authorization: Bearer <67efe163fe3afbe0781fd623>

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###

# Get user by ID
GET http://localhost:8081/user/getUserById
Content-Type: application/json
Authorization: Bearer <67efe163fe3afbe0781fd623>

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###

# Delete a user (Admin only)
DELETE http://localhost:8081/user/deleteUser/635ab8dfc407faf9f73deaf2
Content-Type: application/json
Authorization: Bearer <67efe163fe3afbe0781fd623>

###

# Create a review
POST http://localhost:8081/reviews/createReview
Content-Type: application/json
Authorization: Bearer <67efe163fe3afbe0781fd623>

{
    "username": "John Doe",
    "comment": "Nice!",
    "rating": 5
}

###

# Delete a review (Admin only)
DELETE http://localhost:8081/reviews/deleteReview/67d45fbaccd71ca4fe7b1234
Content-Type: application/json
Authorization: Bearer <67efe163fe3afbe0781fd623>

###

# Delete all users (Admin only)
POST http://localhost:8081/user/deleteAll
Content-Type: application/json
Authorization: Bearer <67efe163fe3afbe0781fd623>
