POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll 

###
POST http://localhost:8081/reviews/createReview
Content-Type: application/json

{
    "username": "John Doe",
    "comment": "Nice!",
    "rating": 5
}

###
PUT http://localhost:8081/reviews/updateReview/67d1ac5360996470c48560c3
Content-Type: application/json

{
    "username": "UpdatedUser",
    "comment": "This is an updated review!",
    "rating": 5
}

###
DELETE http://localhost:8081/reviews/deleteReview/67d45033d20220d68e8970cf

###
GET http://localhost:8081/reviews/getReview/67cf3e178e7b872479769e7f


